### ISSUE TITLE
训练相关问题

### ISSUE THREAD

**Issue by BurstLink666** [liuzywen/RGBTCC#10]
在训练数据处理中，部分代码：
  # m = int(width / 224)
    # n = int(height / 224)
    # fname = img_path.split('/')[-1]
    # root_path = img_path.split('IMG_')[0].replace('images', 'images_crop')

    # kpoint = kpoint.copy()
    # if root_path.split('/')[-3] == 'train_data':
    #
    #     for i in range(0, m):
    #         for j in range(0, n):
    #             crop_img = Img_data[j * 224: 224 * (j + 1), i * 224:(i + 1) * 224, ]
    #             crop_kpoint = kpoint[j * 224: 224 * (j + 1), i * 224:(i + 1) * 224]
    #             gt_count = np.sum(crop_kpoint)
    #
    #             save_fname = str(i) + str(j) + str('_') + fname
    #             save_path = root_path + save_fname

                # h5_path = save_path.replace('.jpg', '.h5').replace('images', 'gt_density_map')
                # if gt_count == 0:
                #     print(save_path, h5_path)
                # with h5py.File(h5_path, 'w') as hf:
                #     hf['gt_count'] = gt_count

                # cv2.imwrite(save_path, crop_img)
已经将图像分割为6块224*224的crop并按i、j为文件名保存，但是在训练代码中，没有读取这些文件，而是直接在原图上使用random crop来训练，这是为什么？

我按照原始代码结构进行训练，模型的结果和你们提供的权重的结果相差很多，是需要在数据读取部分做修改吗？

**Comment by ElderWu** [comment]
你好，这部分是注释掉的代码，处理数据时未用到这部分的功能，训练采用随机切割的方式进行训练，缩短训练时间。在测试过程中对图片进行切块处理。结果相差较多可能和数据集的处理方式有关，需要将数据集预处理之后再读取。

**Comment by BurstLink666** [comment]
感谢回复！这部分注释掉后对训练集、验证集、测试集预处理，但训练的最好的结果只能到16.37，测试时的指标也很差。
