### ISSUE TITLE
官方数据运行test.sh报错，outputs生成过程报错out of index

### ISSUE THREAD

**Issue by TakiToolu** [liuzywen/RGBTCC#7]
您好，按照readme跑完train.py顺利执行
train.sh输出结果：
<img width="650" alt="屏幕截图 2024-04-21 155342" src="https://github.com/liuzywen/RGBTCC/assets/66070813/556d356e-704c-4cb1-9d09-10bb0be6c332">

用给的test.sh和给的数据集跑测试的时候生成outputs时报错，尝试将outputs信息打印了出来，报错显示不存在outputs[4]
报错：
<img width="449" alt="test报错" src="https://github.com/liuzywen/RGBTCC/assets/66070813/604faee0-1913-4085-9501-b6a8ab44dd89">

打印outputs信息：
<img width="430" alt="打印ouputs" src="https://github.com/liuzywen/RGBTCC/assets/66070813/168f9e31-2c7a-44bb-aefa-93acccaef54d">

辛苦您百忙之中帮忙定位下问题，多谢！

**Comment by ElderWu** [comment]
你好，请问将训练集，验证集，测试集的图片缩放到672 X 448的尺寸了吗？因为测试的时候需要将图片切成6个224 X 224大小的小块，如果尺寸不对的话，可能切不了这么多块，导致outpus[4]和outputs[5]为空，outputs的长度为4而不是6。

**Comment by TakiToolu** [comment]
调整尺寸通过了，感谢解答
